# Generated by Django 3.2 on 2021-05-23 10:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('point_start', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, serialize=False, spatial_index=False, srid=4326, verbose_name='Start coordinates')),
                ('point_end', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, serialize=False, spatial_index=False, srid=4326, verbose_name='End coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_speed', models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Average speed')),
                ('intensity', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Intensity')),
                ('characterization', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, verbose_name='Characterization')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_record', to='road_segments.segment')),
            ],
        ),
    ]
